services:
  weather-frontend:
    build:
      context: ./weather-frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./weather-frontend/src:/home/node/app/src
    command: ["npm", "start"]
    networks:
      default: { ipv4_address: 10.23.1.0 }
    depends_on:
      - weather-change-aggregator

  # run under "https://app-hostname/next" path
  weather-next:
    build:
      context: ./weather-next
      dockerfile: Dockerfile
    volumes:
      - ./weather-next/src:/home/node/app/src
    command: ["npm", "run", "dev"]
    networks:
      default: { ipv4_address: 10.23.1.1 }
    depends_on:
      - weather-change-aggregator

  weather-change-aggregator:
    build:
      context: ./weather-change-aggregator
      dockerfile: Dockerfile
    environment:
      WA_WS_URL: "ws://weather-stream-simulator:8765"
      WA_HTTP_PORT: 3000
      WA_HTTP_HOSTNAME: "0.0.0.0"
      WA_MONGODB_URL: "mongodb://mongo/weather-change-aggregator"
      WA_LOGGER_LEVEL: "info"
      WA_SYNC_MS: 20000
    command: ["npm", "run", "start:watch"]
    networks:
      default: { ipv4_address: 10.23.2.10 }
    volumes:
      - ./weather-change-aggregator/src:/home/node/app/src
    depends_on:
      - weather-stream-simulator
      - mongo

  weather-stream-simulator:
    build:
      context: ./weather-stream-simulator
      dockerfile: Dockerfile
    command: npm start

  mongo:
    init: true
    image: mongo:8-noble
    networks:
      default: { ipv4_address: 10.23.0.10 }
    volumes: [ "mongodb:/data/db", "mongodb-config:/data/configdb" ]

volumes:
  mongodb:
  mongodb-config:

networks:
  default:
    name: ww-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.0.0/16
